Insert into REQUISITI (name, obbligatoriety, description) values 
("R0V1.2", "Obbligatorio", "L'applicativo dovrà essere sviluppato con JavaScript 8 (ES8)"), 
("R0Q1", "Obbligatorio", "La progettazione e il codice devono seguire le norme e le metriche riportate nel documento allegato \pdq \vruno"), 
("R0Q5", "Obbligatorio", "Dovrà essere fornito un manuale utente in lingua inglese che tratterà l'uso da parte di studenti e professori"), 
("R0V6", "Obbligatorio", "L'applicativo deve essere accessibile ed utilizzabile dal browser Google Chrome a partire dalla versione 57"), 
("R0F5.1.4", "Obbligatorio", "Uno studente può ottenere il totale dei suoi crediti"), 
("R0V3", "Obbligatorio", "La connessione alla rete Ethereum deve avvernire tramite MetaMask"), 
("R0V1.3", "Obbligatorio", "L'applicativo dovrà essere sviluppato con il boilerplate Redux Minimal"), 
("R0F5.2.1", "Obbligatorio", "Uno studente può ottenere il numero di crediti degli esami opzionali"), 
("R0Q6", "Obbligatorio", "Dovrà essere fornito un manuale di deploy e di utilizzo da parte degli amministratori in lingua inglese"), 
("R0V8", "Obbligatorio", "Un utente non deve poter compiere azioni sul sistema senza aver fatto l'accesso ad esso"), 
("R0F2.1", "Obbligatorio", "L'amministratore può ottenere una lista di tutti i professori"), 
("R1V7", "Desiderabile", "L'applicativo deve essere accessibile ed utilizzabile da un browser mobile, per le versioni supportate fare riferimento alle controparti PC di Firefox e Chrome"), 
("R0F4.1", "Obbligatorio", "Un professore può ottenere la lista di tutti gli esami a lui assegnati"), 
("R0F11.1", "Obbligatorio", "L'università deve poter aggiungere amministratori"), 
("R0V1", "Obbligatorio", "L'applicativo dovrà essere sviluppato attraverso l'uso di tecnologie web"), 
("R0F3.3.1", "Obbligatorio", "L'amministratore può creare un nuovo corso di laurea a partire da un anno accademico"), 
("R0Q3", "Obbligatorio", "Il codice JavaScript deve attenersi al airbnb JavaScript style guide"), 
("R0V4", "Obbligatorio", "Lo sviluppo degli smart contract dovrà avvenire utilizzando il framework Truffle"), 
("R0V9", "Obbligatorio", "'applicazione dei principi de \"App a 12 Fattori\" deve essere documentato ove possibile l'utilizzo"), 
("R0F3.3.2", "Obbligatorio", "L'amministratore può ottenere una lista di tutti i corsi di laurea dato un anno accademico"), 
("R0V1.5", "Obbligatorio", "L'applicativo dovrà essere sviluppato utilizzando Redux"), 
("R0F1", "Obbligatorio", "L'amministratore può gestire gli utenti"), 
("R0F3.3.4.2 ", "Obbligatorio", "L'amministratore può associare ad un esame il relativo professore"), 
("R0F3.1", "Obbligatorio", "L'amministratore può aggiungere un anno accademico"), 
("R0F11", "Obbligatorio", "L'università deve poter gestire gli amministratori"), 
("R0F5.1.1", "Obbligatorio", "Uno studente può ottenere il numero di crediti assegnati agli esame"), 
("R0Q7", "Obbligatorio", "Il codice sorgente deve essere pubblicato sulla piattaforma GitHub, BitBucket o GitLab"), 
("R0V1.4", "Obbligatorio", "L'applicativo dovrà essere sviluppato utilizzando React"), 
("R1F9", "Desiderabile", "L'utente può leggere una breve guida sull'uso di MetaMask e sul pagamento delle operazioni"), 
("R2V3.3", "Opzionale", "È apprezzabile un deploy finale sulla rete principale di Ethereum"), 
("R0F3.3.3", "Obbligatorio", "L'amministratore può creare nuovi esami"), 
("R0V3.2", "Obbligatorio", "Il deploy degli smart contract dovrà avvenire su rete locale testrpc e rete di test Ropsten"), 
("R0F4.3", "Obbligatorio", "Un professore può registrare un esito ad un dato esame ad un dato studente registrato a quell'esame"), 
("R0Q2.1", "Obbligatorio", "L'applicativo non deve fare uso di callback in presenza di alternative alle ultime"), 
("R0V2", "Obbligatorio", "Gli smart contract dovranno essere scritti in linguaggio Solidity"), 
("R0V3.1", "Obbligatorio", "I test riguartandi gli smart contract dovranno essere eseguiti in una rete locale ed almeno in una rete pubblica"), 
("R0Q4", "Obbligatorio", "Lo sviluppo deve essere supportato dall'utilizzo del tool ESLint"), 
("R0F6.1", "Obbligatorio", "Il login deve avvenire tramite il controllo delle chiavi, senza ulteriori azioni da parte dell'utente"), 
("R0Q8", "Obbligatorio", "Il codice deve attenersi il più possibile alle guide linea de \"App a 12 Fattori\""), 
("R0F5.1", "Obbligatorio", "Uno studente può vedere l'elenco degli esami ai quali è iscritto"), 
("R0F5.2.2", "Obbligatorio", "Uno studente può iscriversi ad un esame opzionale"), 
("R0F2", "Obbligatorio", "L'amministratore può gestire i professori"), 
("R0F5.2", "Obbligatorio", "Uno studente può ottenere l'elenco degli esami opzionali"), 
("R0V1.7", "Desiderabile", "È desiderabile l'utilizzo di SCSS in sostituzione a CSS"), 
("R0F11.2", "Obbligatorio", "L'università deve poter rimuovere amministratori"), 
("R0F8.1", "Obbligatorio", "La registrazione necessita di nome, cognome, categoria (studente o professore) e selezione del corso di laura se si tratta di uno studente"), 
("R0F6", "Obbligatorio", "L'utente può effettuare il login"), 
("R0V1.6", "Obbligatorio", "Il deploy del sito andrà eseguito utilizzando Surge.sh"), 
("R0F5.1.5", "Obbligatorio", "Uno studente può ottenere il numero di crediti da raggiungere per la laurea"), 
("R0F8", "Obbligatorio", "L'utente non ancora registrato può registrarsi"), 
("R0F10", "Obbligatorio", "L'utente deve poter vedere preventivamente il costo in Gas, Ether e Euro dell'operazione che sta per eseguire"), 
("R0F1.4", "Obbligatorio", "L'amministratore può ottenere una lista di tutti gli studenti"), 
("R0F5.1.2", "Obbligatorio", "Uno studente può ottenere l'obbligatorietà degli esame"), 
("R0F3.2", "Obbligatorio", "L'amministratore può ottenere una lista degli anni accademici"), 
("R0F5.1.3", "Obbligatorio", "Uno studente può ottenere lo stato di superamento degli esame"), 
("R0F11.3", "Obbligatorio", "L'università deve poter ottenere la lista di tutti gli amministratori"), 
("R0Q2", "Obbligatorio", "L'approccio di scrittura di JavaScript deve essere promise Centric Approach"), 
("R0V1.1", "Obbligatorio", "L'applicativo necessiterà della piattaforma Node.js per soddisfare le dipendenze delle librerie richieste citate nei requisiti sottostanti."), 
("R0V5", "Obbligatorio", "L'applicativo deve essere accessibile ed utilizzabile dal browser Mozilla Firefox a partire dalla versione 52"), 
("R0F4", "Obbligatorio", "Un professore può gestire gli esami a lui assegnati"), 
("R0F7", "Obbligatorio", "L'utente può effettuare il logout"), 
("R0F2.2", "Obbligatorio", "L'amministratore può assegnare un esame ad un determinato professore"), 
("R0F5", "Obbligatorio", "Uno studente può gestire l'iscrizione agli esami"), 
("R0V10", "Obbligatorio", "Il codice sorgente deve essere pubblicato con licenza MIT"), 
("R0F3.3", "Obbligatorio", "L'amministratore può gestire i corsi di laurea relativi agli anni accademici"), 
("R0F3.3.4.1", "Obbligatorio", "L'amministratore può ottenere l'informazione di quale professore è assegnato a un determinato esame"), 
("R0F1.2", "Obbligatorio", "L'amministratore può abilitare un utente"), 
("R0F4.2", "Obbligatorio", "Un professore può ottenere la lista di tutti gli studenti associati a un determinato esame"), 
("R0F1.1", "Obbligatorio", "L'amministratore può ottenere una lista di tutti gli utenti non abilitati"), 
("R0F1.3", "Obbligatorio", "L'amministratore può rimuovere un utente"), 
("R0F3.3.4", "Obbligatorio", "L'amministratore può ottenere una lista di tutti gli esami dato il corso di laurea"), 
("R0F3", "Obbligatorio", "L'amministratore può gestire gli anni accademici")
;
Insert into UC (name, description) values 
("UC2", "Login"), 
("UC3.4", "Selezione corso"), 
("UC5.3.10.1", "Visualizzazione lista di esami non ancora assegnati"), 
("UC8.1", "Aggiunta di un amministratore"), 
("UC7.1.2", "Visualizzazione della obbligatorietà degli esami ai quali è iscritto"), 
("UC3.8", "Visualizzazione errore MetaMask non installato"), 
("UC8.1.2", "Visualizzazione messaggio di errore riguardo a chiave mal formata"), 
("UC3.2", "Inserimento cognome"), 
("UC4", "Logout"), 
("UC5.1.2", "Visualizzazione lista di professori"), 
("UC5.3", "Gestione corsi di laurea"), 
("UC5.3.9", "Visualizzazione dettagli esame"), 
("UC7.1", "Visualizzazione lista degli esami"), 
("UC2.3", "Visualizzazione messaggio di errore riguardo a MetaMask assente"), 
("UC8.1.3", "Visualizzazione messaggio di errore riguardo a chiave già registrata"), 
("UC5.2", "Gestione anni accademici"), 
("UC5.3.2", "Visualizzazione errore sigla invalida"), 
("UC6.3", "Registrazione valutazione di un esame"), 
("UC5.3.1", "Creazione \citGloss{corso di laurea}"), 
("UC5.3.8", "Visualizzazione lista esami"), 
("UC5.3.10", "Associazione professore a esame"), 
("UC3.3", "Selezione categoria"), 
("UC3.1", "Inserimento nome"), 
("UC5.1.5", "Rimozione utente"), 
("UC5.2.3", "Visualizzazione messaggio anno malformato"), 
("UC7.1.1", "Visualizzazione dei crediti degli esami ai quali è iscritto"), 
("UC3", "Registrazione"), 
("UC5.3.10.2", "Visualizzazione lista professori selezionato un esame"), 
("UC5.3.6", "Visualizzazione errore nome esame non valido"), 
("UC5.1.3", "Visualizzazione di utenti non abilitati"), 
("UC5.3.10.3", "Associazione professore all'esame"), 
("UC3.7", "Visualizzazione errore chiave non presente"), 
("UC8", "Gestione degli amministratori"), 
("UC3.5", "Visualizzazione errore campo non compilato"), 
("UC7.2", "Visualizzazione degli esami opzionali e dei loro crediti"), 
("UC5.3.7", "Visualizzazione lista esami per \citGloss{corso di laurea}"), 
("UC2.1", "Login automatico"), 
("UC6", "Gestione aspetti relativi agli esami"), 
("UC8.2", "Visualizzazione lista degli amministratori"), 
("UC1", "Breve guida"), 
("UC6.1", "Visualizzazione lista degli esami"), 
("UC5.1.1", "Visualizzazione lista di studenti"), 
("UC2.2", "Visualizzazione messaggio di errore riguardo a chiave assente"), 
("UC5.3.4", "Visualizzazione lista corsi di laurea per \citGloss{anno accademico}"), 
("UC5.2.4", "Visualizzazione messaggio di \citGloss{anno accademico} già presente"), 
("UC6.2", "Visualizzazione lista degli studenti"), 
("UC7", "Gestione aspetti relativi allo studente"), 
("UC5.3.5", "Creazione esame in un corso"), 
("UC2.4", "Visualizzazione messaggio di errore riguardo a chiave non registrata"), 
("UC3.6", "Visualizzazione errore utente già registrato"), 
("UC7.3", "Registrazione ad un esame opzionale"), 
("UC5.1", "Gestione Utenti"), 
("UC5.1.4", "Abilitazione utente"), 
("UC7.4", "Visualizzazione delle informazioni relative ai crediti"), 
("UC5", "Amministrazione"), 
("UC5.2.2", "Visualizzazione lista di tutti gli anni accademici"), 
("UC8.3", "Rimozione amministratore"), 
("UC5.2.5", "Visualizzazione messaggio anno non compilato"), 
("UC8.1.1", "Inserimento \citGloss{chiave pubblica}"), 
("UC9", "Visualizzazione quantità di \citGloss{Gas}, \citGloss{Ether} e costo delle operazioni"), 
("UC5.3.3", "Visualizzazione lista completa dei corsi"), 
("UC5.2.1", "Aggiunta \citGloss{anno accademico}")
;
Insert into UCR (uc, r) values 
("UC5", "R0F3"), 
("UC3.2", "R0F8.1"), 
("UC2", "R0F6"), 
("UC6.2", "R0F4.2"), 
("UC3.7", "R0F8.1"), 
("UC7.3", "R0F5.2.2"), 
("UC3.4", "R0F8.1"), 
("UC3.8", "R0F8.1"), 
("UC7.1.1", "R0F5.1.1"), 
("UC7.1", "R0F5.1"), 
("UC3", "R0F8"), 
("UC5.3.10", "R0F3.3.4.2"), 
("UC5.2.2", "R0F3.2"), 
("UC8.3", "R0F11.2"), 
("UC5.2.1", "R0F3.1"), 
("UC7.2", "R0F5.2"), 
("UC5.1.3", "R0F1.1"), 
("UC5.3.1", "R0F3.3.1"), 
("UC5.1.5", "R0F1.3"), 
("UC5.3.8", "R0F3.3.4"), 
("UC5.3.9", "R0F3.3.4.1"), 
("UC8.2", "R0F11.3"), 
("UC5.3.6", "R0F3.3.3"), 
("UC6.1", "R0F4.1"), 
("UC5.3.4", "R0F3.3.2"), 
("UC3.1", "R0F8.1"), 
("UC5.2.3", "R0F3.1"), 
("UC6.3", "R0F4.3"), 
("UC5.3.5", "R0F3.3.3"), 
("UC1", "R1F9"), 
("UC5.3.10.1", "R0F3.3.4.2"), 
("UC6", "R0F4"), 
("UC7.1.2", "R0F5.1.2"), 
("UC5.2.4", "R0F3.1"), 
("UC5.2.5", "R0F3.1"), 
("UC5.3.7", "R0F3.3.4"), 
("UC5.1.4", "R0F1.2"), 
("UC5.3.3", "R0F3.3.2"), 
("UC5.3.10.3", "R0F3.3.4.2"), 
("UC2.3", "R0F6.1"), 
("UC3.3", "R0F8.1"), 
("UC5.2", "R0F3"), 
("UC2.2", "R0F6.1"), 
("UC5.1.2", "R0F2.1"), 
("UC7", "R0F5"), 
("UC7.4", "R0F5.1.4"), 
("UC9", "R0F10"), 
("UC3.5", "R0F8.1"), 
("UC3.6", "R0F8.1"), 
("UC4", "R0F7"), 
("UC5.3", "R0F3.3"), 
("UC7.4", "R0F5.2.1"), 
("UC2.4", "R0F6.1"), 
("UC5.3.2", "R0F3.3.1"), 
("UC8.1.2", "R0F11.1"), 
("UC5", "R0F1"), 
("UC8", "R0F11"), 
("UC8.1.3", "R0F11.1"), 
("UC5.3.10.2", "R0F3.3.4.2"), 
("UC5.1", "R0F1"), 
("UC2.1", "R0F6.1"), 
("UC5", "R0F2"), 
("UC8.1", "R0F11.1"), 
("UC5.1.1", "R0F1.4"), 
("UC8.1.1", "R0F11.1")
;
