This is makeindex, version 2.15 [MiKTeX 2.9.6500 64-bit] (kpathsea + Thai support).
Scanning style file ./GlossarioEST.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file GlossarioEST.acn....done (94 entries accepted, 0 rejected).
Sorting entries....done (639 comparisons).
Generating output file GlossarioEST.acr....done (205 lines written, 0 warnings).
Output written in GlossarioEST.acr.
Transcript written in GlossarioEST.alg.
